[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-framework-ext"
version = "0.1.0"
description = "An extension package"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/my_framework_ext"]
